### ISSUE TITLE
Dgs-webflux build problem

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [hantsy/spring-graphql-sample#675]
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method dgsReactiveQueryExecutor in com.netflix.graphql.dgs.webflux.autoconfiguration.DgsWebFluxAutoConfiguration required a bean of type 'graphql.schema.GraphQLSchema' that could not be found.


Action:

Consider defining a bean of type 'graphql.schema.GraphQLSchema' in your configuration.

```

Yml
```
spring:
  main:
    web-application-type: reactive
  autoconfigure:
    exclude: com.netflix.graphql.dgs.autoconfig.DgsAutoConfiguration

dgs:
  graphql:
    schema-locations: classpath*:graphql/**/*.graphql*
    path: /graphql
```
The version is same like you but use kt
